global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO.Compression;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Xml.Serialization;

global using Snap.Engine.Assets.Fonts;
global using Snap.Engine.Assets.LDTKImporter;
global using Snap.Engine.Assets.LDTKImporter.Instances;
global using Snap.Engine.Assets.LDTKImporter.Settings;
global using Snap.Engine.Assets.Loaders;
global using Snap.Engine.Assets.Spritesheets;
global using Snap.Engine.Beacons;
global using Snap.Engine.Coroutines;
global using Snap.Engine.Coroutines.Routines.Animations;
global using Snap.Engine.Coroutines.Routines.Conditionals;
global using Snap.Engine.Coroutines.Routines.Time;
global using Snap.Engine.Entities;
global using Snap.Engine.Entities.Graphics;
global using Snap.Engine.Entities.Panels;
global using Snap.Engine.Enums;
global using Snap.Engine.Graphics;
global using Snap.Engine.Graphics.Atlas;
global using Snap.Engine.Helpers;
global using Snap.Engine.Inputs;
global using Snap.Engine.Logs;
global using Snap.Engine.Resources;
global using Snap.Engine.Screens;
global using Snap.Engine.Services;
global using Snap.Engine.Sounds;
global using Snap.Engine.Systems;
global using Snap.Engine.Tweens;

global using SFBlendMode = SFML.Graphics.BlendMode;
global using SFClock = SFML.System.Clock;
global using SFColor = SFML.Graphics.Color;
global using SFContext = SFML.Window.ContextSettings;
global using SFImage = SFML.Graphics.Image;
global using SFJoystick = SFML.Window.Joystick;
global using SFJoystickAxis = SFML.Window.Joystick.Axis;
global using SFJoystickButtonEventArgs = SFML.Window.JoystickButtonEventArgs;
global using SFJoystickConnectEventArgs = SFML.Window.JoystickConnectEventArgs;
global using SFJoystickIdentification = SFML.Window.Joystick.Identification;
global using SFKey = SFML.Window.Keyboard.Key;
global using SFKeyboard = SFML.Window.Keyboard;
global using SFKeyEventArgs = SFML.Window.KeyEventArgs;
global using SFMouse = SFML.Window.Mouse;
global using SFMouseButton = SFML.Window.Mouse.Button;
global using SFMouseButtonEventArgs = SFML.Window.MouseButtonEventArgs;
global using SFPrimitiveType = SFML.Graphics.PrimitiveType;
global using SFRectF = SFML.Graphics.FloatRect;
global using SFRectI = SFML.Graphics.IntRect;
global using SFRenderStates = SFML.Graphics.RenderStates;
global using SFRenderTexture = SFML.Graphics.RenderTexture;
global using SFRenderWindow = SFML.Graphics.RenderWindow;
global using SFSound = SFML.Audio.Sound;
global using SFSoundBuffer = SFML.Audio.SoundBuffer;
global using SFSoundStatus = SFML.Audio.SoundStatus;
global using SFSprite = SFML.Graphics.Sprite;
global using SFStyles = SFML.Window.Styles;
global using SFTexture = SFML.Graphics.Texture;
global using SFTime = SFML.System.Time;
global using SFTransform = SFML.Graphics.Transform;
global using SFVectF = SFML.System.Vector2f;
global using SFVectI = SFML.System.Vector2i;
global using SFVectU = SFML.System.Vector2u;
global using SFVertex = SFML.Graphics.Vertex;
global using SFVertexBuffer = SFML.Graphics.VertexBuffer;
global using SFVideoMode = SFML.Window.VideoMode;
global using SFView = SFML.Graphics.View;